/** Rebuild the native career component from its reviewed, adapted sources. No eval or runtime compilation. */
import {build} from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=fileURLToPath(new URL('../site/apps/career/',import.meta.url));
const built=await build({entryPoints:[path.join(root,'assets/app.js')],bundle:true,format:'iife',globalName:'CareerRuntime',platform:'browser',target:['es2022'],write:false,legalComments:'none',logLevel:'warning'});
const bindings='document, window, localStorage, location, navigator, fetch, MutationObserver, URL, setTimeout, clearTimeout, requestAnimationFrame, confirm, prompt';
const output=`/* Generated by scripts/build-career.mjs. Each call creates isolated state and scoped browser capabilities. */\nexport function createCareerRuntime(__careerHost) {\nconst {${bindings}} = __careerHost;\n${built.outputFiles[0].text}\nreturn CareerRuntime;\n}\n`;
await fs.writeFile(path.join(root,'runtime.bundle.mjs'),output);
const cssFiles=['styles.css','workspace.css','classroom.css','decision-lab.css','public-service.css','stage8.css','vacancies.css','release.css'];
let css=(await Promise.all(cssFiles.map(file=>fs.readFile(path.join(root,'assets',file),'utf8')))).join('\n');
css=css.replace(/url\((['"]?)\.\/fonts\//g,'url($1assets/fonts/');
css=css.replace(/html(:lang\([^)]*\)|\[lang=[^\]]*\])\s+body/g,'.career-surface$1');
css=css.replace(/:root\b/g,'.career-surface').replace(/\bhtml\b/g,'.career-surface').replace(/\bbody\b/g,'.career-surface');
// The containing course column, rather than viewport width, controls the component layout.
css=css.replace(/@media\s*(\((?:max|min)-width\s*:[^)]*\))/g,'@container career $1');
css+='\n'+await fs.readFile(path.join(root,'embedded.css'),'utf8');
await fs.writeFile(path.join(root,'module.css'),css);
console.log('Built native career runtime and Shadow DOM stylesheet.');
