#!/usr/bin/env python3
"""Apply the module's responsive rules to its available width inside the course."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
module = root / 'site/apps/reception'
source = (module / 'style.css').read_text(encoding='utf-8')
rules = []
for match in re.finditer(r'@media\s*([^{}]+)\{', source):
    condition = match.group(1).strip()
    if not re.search(r'(?:min|max)-width', condition):
        continue
    start = end = match.end()
    depth = 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    body = source[start:end-1].replace('.reception-root', '.reception-page .reception-root')
    rules.append('@container reception ' + condition + '{' + body + '}')

base = '''/* Generated by scripts/build-reception-native-css.py. */
.reception-page{container:reception / inline-size;min-width:0;}
.reception-page .reception-root{min-width:0;overflow:clip;}
.reception-page .reception-root .rx-logo{display:none;}
.reception-page .reception-root .rx-brand{border-left:0;padding-left:0;}
'''
offsets = '''
/* The course keeps its fixed top bar and mobile navigation. */
.reception-page .reception-root .rx-profile{display:flex;}
.reception-page .reception-root .rx-nav{top:var(--top,76px);}
.reception-page .reception-root .rx-panel h2,
.reception-page .reception-root .rx-hero h1,
.reception-page .reception-root .rx-summary h1,
.reception-page .reception-root .rx-bank-heading h2{scroll-margin-top:calc(var(--top,76px) + 24px);}
@container reception (max-width:760px){
 .reception-page .reception-root .rx-panel h2{scroll-margin-top:calc(var(--top,64px) + 120px);}
 .reception-page .reception-root .rx-doc-item{grid-template-columns:minmax(0,1fr);}
 .reception-page .reception-root .rx-doc-item .rx-doc-button{min-height:54px;justify-content:flex-start;text-align:left;font-size:14px;}
 .reception-page .reception-root .rx-doc-item>.rx-btn.ghost{justify-content:flex-start;padding:8px 12px;}
 .reception-page .reception-root .rx-doc-grid{gap:14px;}
}
'''
(module / 'platform.css').write_text(base + '\n'.join(rules) + offsets, encoding='utf-8')
print('Reception: native responsive stylesheet generated.')
