#!/usr/bin/env node
/** An inventory derived from existing author material, NOT a new legal validation. */
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {SOURCES,CASE_TEMPLATES} from '../site/apps/reception/js/cases.js';
import {EVIDENCE_RECORDS,EVIDENCE_TASKS,EVIDENCE_VERSION} from '../site/apps/reception/js/evidence-catalog.js';
import {SOURCE_POLICY} from '../site/apps/reception/js/source-policy.js';
const base=fileURLToPath(new URL('../',import.meta.url));
const family=c=>c.curriculumId|| (Number.isInteger(c.originVariant)?'F'+String(c.originVariant).padStart(2,'0'):'extension');
const sourceRefs=c=>new Set([...(c.sourceIds||[]),c.knowledge?.sourceId,c.lawId,c.orgId,...(c.feedbackSources||[])]);
const fingerprint=r=>createHash('sha256').update(JSON.stringify(r)).digest('hex');
const rows=[...SOURCES.map(record=>({record,collection:'shelf'})),...EVIDENCE_RECORDS.map(record=>({record,collection:'evidence'}))].map(({record:r,collection})=>{
 const related=CASE_TEMPLATES.filter(c=>collection==='shelf'?sourceRefs(c).has(r.id):(EVIDENCE_TASKS[c.evidenceTaskId]?.recordIds||[]).includes(r.id));
 const synthetic=collection==='evidence'&&/(?:Учебн(?:ый|ые|ая)|вымышлен)/i.test(r.kind||'');
 const volatile=/контакт/i.test(r.kind||'')||r.kind==='organisation'||r.kind==='Официальный сайт';
 const checked=r.asOf||null;
 return {id:collection+':'+r.id,recordId:r.id,collection,title:r.title||r.short||r.id,url:r.url||'',kind:synthetic?'authored-case':volatile?'directory':'normative-material',originalKind:r.kind||'law',scope:r.scope||'См. условия источника',contentSHA256:fingerprint(r),inheritedCheckedAt:checked,reviewProvenance:'inherited-from-0.16; not independently revalidated',reviewIntervalDays:synthetic?null:volatile?30:180,families:[...new Set(related.map(family))].sort(),cases:related.map(c=>({id:c.id,title:c.title})),rules:SOURCE_POLICY.filter(p=>p.urlIncludes.some(q=>(r.url||'').includes(q))).map(p=>p.id)};
});
const registry={schema:1,version:'source-inventory-2026-09-08.1',evidenceVersion:EVIDENCE_VERSION,createdAt:'2026-09-08',policy:'Inventory date is not legal review date. Synthetic material links are normative context, not proof of a fictional event.',entries:rows};
writeFileSync(base+'SOURCE_INDEX.json',JSON.stringify(registry,null,2)+'\n');
writeFileSync(base+'site/apps/reception/js/source-index.js','// Generated by scripts/build_source_index.mjs.\nexport const SOURCE_INDEX='+JSON.stringify(registry)+';\n');
console.log(JSON.stringify({entries:rows.length,distinctUrls:new Set(rows.map(x=>x.url).filter(Boolean)).size,authoredCase:rows.filter(r=>r.kind==='authored-case').length}));
