#!/usr/bin/env python3
"""Graded Russia map falls back locally when its original geometry fails.

Run in CI with the existing PuzzleServer's loopback-only identity, unchanged
grading/storage code and read-only engine observation hook. Browser service
workers are blocked so a previous cache cannot conceal a first-visit dependency.
Every completion uses pointer input, never an engine setter/completion shortcut.
The two legacy fixtures are generated by actual play of the original TopoJSON;
only their explicitly documented storage schema/cache faults are then seeded.
"""
from __future__ import annotations

import argparse
import asyncio
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import time
import traceback
from urllib.parse import urlsplit

from playwright.async_api import async_playwright
from test_puzzle_catalog import (
    PuzzleServer, ROOT, STUDENT, check_layout, initializer, place_pieces, ready,
    trusted_drop,
)

SITE = ROOT / 'site'
GEOMETRY_PATH = '/RUDN/assets/puzzle/data/russia_subjects_89.topojson'
COMPACT_PATH = '/RUDN/assets/puzzle/data/russia_subjects_89.compact.json'
OWNER = 'student:' + STUDENT['studentKey']
SCOPE = {'owner': OWNER, 'activitySlug': 'seminar-2', 'mode': 'seminar'}


def pending_geometry_storage(kind):
    """Stall only the optional map cache; keep student progress storage real."""
    return """(()=>{
      const kind=%s, name='rudn-puzzle-geometry-v1';
      window.__qaGeometryFaultHits=[];
      const hit=stage=>window.__qaGeometryFaultHits.push(stage);
      const open=IDBFactory.prototype.open;
      IDBFactory.prototype.open=function(database,...args){
        if(database===name&&kind==='open') {hit('open');return {};}
        if(database===name&&kind==='cache') {hit('idb-unavailable');throw new Error('QA optional geometry IDB unavailable');}
        return open.call(this,database,...args);
      };
      const transaction=IDBDatabase.prototype.transaction;
      IDBDatabase.prototype.transaction=function(stores,mode,...args){
        if(this.name===name&&mode==='readwrite'&&kind==='write'){
          hit('write');
          // Browser never delivers request success or transaction completion.
          // Its abort surface remains available to the deadline cleanup.
          const tx={objectStore:()=>({put:()=>({})}),abort(){this.onabort?.();}};
          return tx;
        }
        return transaction.call(this,stores,mode,...args);
      };
      const cacheOpen=CacheStorage.prototype.open;
      CacheStorage.prototype.open=function(cacheName){
        if(cacheName===name&&kind==='cache'){hit('cache');return new Promise(()=>{});}
        return cacheOpen.call(this,cacheName);
      };
    })();""" % json.dumps(kind)


def module_paths():
    """Use the application's actual module identities, including cache versions."""
    source = (SITE / 'assets/js/puzzle-bootstrap.js').read_text('utf-8')
    return {name: 'assets/js/' + re.search(
        rf"from ['\"]\./({re.escape(name)}\.js[^'\"]*)['\"]", source
    ).group(1) for name in ('backend', 'durable-store')}


async def stored(page, base):
    return await page.evaluate("""async ({base,modules,scope})=>{
      const progress=document.querySelector('#geoPuzzleApp').puzzleProgress;
      await progress.capture?.();await progress.flush();
      const {durableStore:store}=await import(base+modules['durable-store']);
      const {backend}=await import(base+modules.backend);
      await store.flush();
      return {draft:await store.loadDraft(scope),
        attempts:await store.listAttempts({owner:scope.owner}),
        pending:await store.listPending({owner:scope.owner,includeDeferred:true}),
        grades:backend.localGrades(),conflicts:await store.listConflicts({owner:scope.owner})};
    }""", {'base': base, 'modules': module_paths(), 'scope': SCOPE})


async def wait_ready(page):
    # Use the shared readiness deadline so a slower CI renderer is not mistaken
    # for a network failure. The loader's actual 12s deadline is not accelerated.
    state = await ready(page)
    assert state['mode'] == 'russia-subjects' and state['total'] == 89, state
    assert len(set(state['featureIds'])) == 89, state['featureIds']
    assert await page.locator('#geoPuzzleApp').get_attribute('data-context') == 'seminar'
    await page.wait_for_function("document.querySelector('#geoPuzzleApp').puzzleProgress.canWrite()")
    await page.locator('#puzzleCanvas').scroll_into_view_if_needed()
    return state


async def seed_legacy_fault(page, base, kind):
    """Preserve actual gameplay; remove geometry persistence before reloading."""
    return await page.evaluate("""async ({base,modules,scope,kind})=>{
      const progress=document.querySelector('#geoPuzzleApp').puzzleProgress;
      await progress.capture?.();await progress.flush();
      // Pagehide must not overwrite the deliberately historical fixture.
      progress.save=()=>Promise.resolve();
      const {durableStore:store}=await import(base+modules['durable-store']);
      const draft=await store.loadDraft(scope),state=structuredClone(draft.state);
      if(kind==='v2-no-ref'){
        state.version=2;delete state.geometryRef;delete state.finishedResult;
        delete state.selections;delete state.view.zoom;
      }
      // Keeping v3 geometryRef while evicting its bytes models device storage
      // eviction. A v2 draft has no ref and must follow its original dataset URL.
      const seeded=await store.checkpoint({...scope,attemptId:draft.attemptId,
        contentVersion:kind==='v2-no-ref'?'puzzle-v2':'puzzle-v3',state},{queue:true});
      await store.flush();
      await new Promise((resolve,reject)=>{
        const open=indexedDB.open('rudn-puzzle-geometry-v1');
        open.onerror=()=>reject(open.error);
        open.onsuccess=()=>{
          const db=open.result;
          if(!db.objectStoreNames.contains('geometry')){db.close();reject(new Error('Missing original geometry store'));return;}
          const tx=db.transaction('geometry','readwrite');tx.objectStore('geometry').clear();
          tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};
        };
      });
      await caches.delete('rudn-puzzle-geometry-v1');
      return seeded;
    }""", {'base': base, 'modules': module_paths(), 'scope': SCOPE, 'kind': kind})


async def finish_and_verify(page, base, record):
    before = await page.evaluate('window.__puzzleRead()')
    recovered = await stored(page, base)
    geometry_ref = recovered['draft']['state'].get('geometryRef')
    assert geometry_ref, 'Recovered attempt has no saved geometry reference'
    saved_geometry = await page.evaluate("""async ref=>{
      const wrapper=await document.querySelector('#geoPuzzleApp').puzzleProgress.loadGeometry(ref);
      const geometry=wrapper?.geometry;
      const collection=Object.values(geometry?.objects||{})
        .find(item=>item.type==='GeometryCollection'&&item.geometries?.length===89);
      return {available:Boolean(geometry),type:geometry?.type,
        featureIds:collection?.geometries.map(feature=>String(feature.id))};
    }""", geometry_ref)
    assert saved_geometry['available'], 'Recovered geometry reference has no map bytes'
    assert saved_geometry['type'] == 'Topology', saved_geometry
    assert saved_geometry['featureIds'] == before['featureIds'], saved_geometry
    request_counts = (len(record['geometryRequests']), len(record['compactRequests']))
    pointer = 'touch' if record['viewport'][0] <= 768 else 'mouse'
    result = await place_pieces(page, 89, pointer)
    assert result['actual'] == 89 - before['placed'], result
    assert result['state']['finished'] and result['state']['placed'] == 89
    await page.locator('#puzzleResultDialog[open]').wait_for()
    await page.evaluate("""async ({base,backendPath})=>{
      const {backend}=await import(base+backendPath);
      window.__qaMapGradeReady=()=>backend.localGrades()['seminar-2']?.points===4 &&
        backend.localAttempts().some(a=>a.id===window.__puzzleRead().attemptId);
    }""", {'base': base, 'backendPath': module_paths()['backend']})
    # wait_for_function polls the return value synchronously. An async
    # predicate returns a truthy Promise and can finish on its first false
    # result, before the real completion bridge has saved the local grade.
    await page.wait_for_function('window.__qaMapGradeReady()')
    final = await stored(page, base)
    assert len(final['attempts']) == 1, final['attempts']
    attempt = final['attempts'][0]
    assert attempt['id'] == before['attemptId']
    assert attempt['recordGrade'] is True and attempt['gradeEligible'] is True
    assert attempt['activitySlug'] == 'seminar-2' and attempt['draftMode'] == 'seminar'
    assert attempt['points'] == 4 and attempt['maxPoints'] == 5
    assert attempt['placed'] == attempt['total'] == 89
    assert attempt['featureIds'] == before['featureIds']
    assert final['grades']['seminar-2']['points'] == 4
    assert final['draft']['phase'] == 'completed' and final['draft']['state']['finished']
    assert not final['conflicts'], final['conflicts']
    pending = final['pending']
    assert sorted(op['type'] for op in pending) == ['attempt', 'checkpoint'], pending
    assert all(op['attemptId'] == attempt['id'] and op['owner'] == OWNER for op in pending)
    assert next(op['payload'] for op in pending if op['type'] == 'attempt') == attempt
    checkpoint = next(op['payload'] for op in pending if op['type'] == 'checkpoint')
    assert checkpoint['phase'] == 'completed' and checkpoint['state']['placed'] == 89
    await check_layout(page, record, 'completed')

    # Reopening with geometry transport still blocked must not duplicate the
    # immutable attempt, grade or delivery operations.
    await page.reload(wait_until='domcontentloaded')
    await wait_ready(page)
    await page.locator('#puzzleResultDialog[open]').wait_for()
    reopened = await stored(page, base)
    for key in ('attempts', 'grades', 'pending', 'draft'):
        assert reopened[key] == final[key], ('Reload changed durable completion', key)
    assert (len(record['geometryRequests']), len(record['compactRequests'])) == request_counts, (
        'Reload redownloaded geometry instead of using the recovered snapshot',
        record['geometryRequests'], record['compactRequests'])
    record['completion'] = {'attemptId': attempt['id'], 'points': attempt['points'],
                            'placed': attempt['placed'], 'deliveryTypes': ['attempt', 'checkpoint'],
                            'unchangedAfterReload': True, 'geometrySnapshotAvailable': True,
                            'reloadWithoutGeometryRequests': True}


CASES = [
    {'name': 'native-primary-success', 'route': 'native', 'fault': 'none', 'viewport': (1366, 900)},
    {'name': 'native-invalid-html', 'route': 'native', 'fault': 'html', 'viewport': (1366, 900)},
    {'name': 'native-fresh-abort', 'route': 'native', 'fault': 'abort', 'viewport': (1366, 900)},
    {'name': 'native-fresh-hang', 'route': 'native', 'fault': 'hang', 'viewport': (1366, 900)},
    {'name': 'native-mobile-abort', 'route': 'native', 'fault': 'abort', 'viewport': (390, 844)},
    {'name': 'standalone-fresh-hang', 'route': 'standalone', 'fault': 'hang', 'viewport': (390, 844)},
    {'name': 'native-legacy-v2-abort', 'route': 'native', 'fault': 'abort',
     'viewport': (390, 844), 'legacy': 'v2-no-ref'},
    {'name': 'native-evicted-v3-hang', 'route': 'native', 'fault': 'hang',
     'viewport': (1366, 900), 'legacy': 'v3-missing-bytes'},
    {'name': 'native-geometry-open-pending', 'route': 'native', 'fault': 'none',
     'viewport': (1366, 900), 'storageFault': 'open'},
    {'name': 'native-geometry-write-pending', 'route': 'native', 'fault': 'none',
     'viewport': (1366, 900), 'storageFault': 'write'},
    {'name': 'native-fallback-geometry-cache-pending', 'route': 'native', 'fault': 'abort',
     'viewport': (1366, 900), 'storageFault': 'cache'},
]


async def run_case(browser, server, output, case):
    record = {**case, 'browser': browser.browser_type.name, 'status': 'failed',
              'serviceWorkers': 'blocked', 'blockedExternal': [], 'blockedWrites': [],
              'geometryRequests': [], 'compactRequests': [], 'pageErrors': []}
    started = time.monotonic()
    context = await browser.new_context(service_workers='block', reduced_motion='reduce',
                                        viewport=dict(zip(('width', 'height'), case['viewport'])),
                                        has_touch=case['viewport'][0] <= 768)
    await context.add_init_script(initializer('ru'))
    if case.get('storageFault'):
        await context.add_init_script(pending_geometry_storage(case['storageFault']))
    original_phase = bool(case.get('legacy'))
    release = asyncio.Event()

    async def intercept(route):
        request = route.request
        parsed = urlsplit(request.url)
        if request.method not in ('GET', 'HEAD'):
            record['blockedWrites'].append({'url': request.url, 'method': request.method})
            await route.abort('blockedbyclient')
            return
        if not request.url.startswith(server.origin + '/'):
            record['blockedExternal'].append(request.url)
            await route.abort('blockedbyclient')
            return
        if parsed.path == GEOMETRY_PATH:
            record['geometryRequests'].append({'phase': 'legacy-seed' if original_phase else 'test',
                                               'fault': None if original_phase else case['fault']})
            if original_phase or case['fault'] == 'none':
                await route.continue_()
            elif case['fault'] == 'abort':
                await route.abort('failed')
            elif case['fault'] == 'html':
                await route.fulfill(status=200, content_type='text/html',
                                    body='<!doctype html><title>Network sign in</title>')
            else:
                await release.wait()
                try:
                    await route.abort('failed')
                except Exception as error:
                    # Its AbortSignal may have already cancelled this hanging
                    # request; only ignore that specific teardown condition.
                    if not any(text in str(error) for text in (
                        'Target page, context or browser has been closed',
                        'Route is already handled', 'Invalid InterceptionId',
                    )):
                        raise
            return
        if parsed.path == COMPACT_PATH:
            record['compactRequests'].append({'phase': 'legacy-seed' if original_phase else 'test'})
        await route.continue_()

    await context.route('**/*', intercept)
    page = await context.new_page()
    page._qa_base = server.base
    page.on('pageerror', lambda error: record['pageErrors'].append(str(error)))
    page.on('dialog', lambda dialog: asyncio.create_task(dialog.accept()))
    try:
        url = server.base + ('index.html#activity/seminar-2' if case['route'] == 'native'
                             else 'apps/puzzle.html?context=seminar')
        await page.goto(url, wait_until='domcontentloaded')
        if case.get('storageFault'):
            # Reproduce the photographed state before waiting for recovery:
            # the real spinner is visible, all 89 regions are still absent.
            await page.locator('#puzzleLoading').wait_for(state='visible')
            spinner_started = time.monotonic()
            loading = await page.evaluate('window.__puzzleRead()')
            assert loading['loading'] and not loading['ready'] and loading['total'] == 0, loading
            record['pendingSpinnerObserved'] = True
            # A cache deadline must bound startup independently of downloads.
            await page.wait_for_function(
                'window.__puzzleRead().ready && !window.__puzzleRead().loading', timeout=20000)
            record['storageRecoverySeconds'] = round(time.monotonic() - spinner_started, 3)
        initial = await wait_ready(page)
        assert initial['difficulty'] == 'medium' and initial['placed'] == 0
        assert initial['ready'] and not initial['loading'] and initial['elapsedMs'] == 0
        record['readySeconds'] = round(time.monotonic() - started, 3)
        await check_layout(page, record, 'ready')
        await trusted_drop(page)
        if case.get('legacy'):
            await trusted_drop(page)
            await page.locator('#puzzleHint').click()
            await page.locator('#puzzleReturn').click()
            seeded = await seed_legacy_fault(page, server.base, case['legacy'])
            assert len(record['geometryRequests']) == 1, record['geometryRequests']
            original_phase = False
            await page.reload(wait_until='domcontentloaded')
            restored = await wait_ready(page)
            for key in ('attemptId', 'order', 'featureIds', 'placed', 'hints', 'difficulty', 'current'):
                assert restored[key] == seeded['state'][key], ('Legacy restore changed state', key)
            assert restored['placed'] == 2 and restored['hints'] == 1
            assert restored['elapsedMs'] >= seeded['state']['elapsedMs']
            record['legacyRestore'] = {'schema': case['legacy'], 'placed': 2,
                                       'sameAttemptOrderAndIds': True, 'originalGeometryPlayed': True}
        if case.get('storageFault'):
            hits = await page.evaluate('window.__qaGeometryFaultHits')
            assert case['storageFault'] in hits, ('Fault was never reached', hits)
            saved = await stored(page, server.base)
            assert saved['draft']['state']['placed'] == 1, saved['draft']
            assert saved['draft']['state']['featureIds'] == initial['featureIds']
            assert not saved['attempts'] and 'seminar-2' not in saved['grades'], saved
            geometry_ref = saved['draft']['state'].get('geometryRef')
            assert geometry_ref, 'The running attempt lost its map reference'
            # A slow disk must not invalidate geometry already held in memory.
            available = await page.evaluate("""async ref=>Boolean(
                (await document.querySelector('#geoPuzzleApp').puzzleProgress.loadGeometry(ref))?.geometry
            )""", geometry_ref)
            assert available, 'In-memory geometry disappeared after optional-cache timeout'
            record['storageRecovery'] = {'faultStages': hits, 'renderedRegions': initial['total'],
                                         'trustedPointerPlaced': 1, 'progressSaved': True,
                                         'inMemoryGeometryAvailable': True}
        else:
            await finish_and_verify(page, server.base, record)
        primary_test = [r for r in record['geometryRequests'] if r['phase'] == 'test']
        compact_test = [r for r in record['compactRequests'] if r['phase'] == 'test']
        assert primary_test, 'Primary geometry path was bypassed'
        if case['fault'] == 'none':
            assert not compact_test, 'Compact map fetched despite healthy original'
        else:
            assert compact_test, 'Original failure did not load the same-origin compact map'
        assert not [r for r in record['compactRequests'] if r['phase'] == 'legacy-seed']
        record['primaryRemainsDefault'] = True
        assert not record['pageErrors'], record['pageErrors']
        assert not record['blockedWrites'], record['blockedWrites']
        record['status'] = 'passed'
        await page.screenshot(path=str(output / (case['name'] + '.png')))
    except Exception as error:
        record['error'] = str(error)
        record['traceback'] = traceback.format_exc()
        try:
            record['lastState'] = await page.evaluate('window.__puzzleRead?.()')
            await page.screenshot(path=str(output / (case['name'] + '-failure.png')), timeout=5000)
        except Exception:
            pass
    finally:
        release.set()
        await context.close()
        record['seconds'] = round(time.monotonic() - started, 3)
    return record


async def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--browsers', default='chromium')
    parser.add_argument('--only', choices=[case['name'] for case in CASES])
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    results = []
    with PuzzleServer(args.output) as server:
        async with async_playwright() as playwright:
            for browser_name in args.browsers.split(','):
                browser_output = args.output / browser_name
                browser_output.mkdir(exist_ok=True)
                browser = await getattr(playwright, browser_name).launch(
                    **({'firefox_user_prefs': {'network.proxy.type': 0}} if browser_name == 'firefox' else {}))
                browser_results = []
                try:
                    for case in CASES:
                        if args.only and case['name'] != args.only:
                            continue
                        record = await run_case(browser, server, browser_output, case)
                        browser_results.append(record)
                        print(json.dumps({'browser': browser_name, 'case': case['name'],
                                          'status': record['status'], 'error': record.get('error')}, ensure_ascii=False), flush=True)
                finally:
                    await browser.close()
                    results.extend(browser_results)
                    (browser_output / 'map-network.json').write_text(json.dumps({
                        'createdAt': datetime.now(timezone.utc).isoformat(),
                        'browser': browser_name, 'cases': browser_results,
                    }, ensure_ascii=False, indent=2), encoding='utf-8')
    if not results or any(record['status'] != 'passed' for record in results):
        raise SystemExit(1)


if __name__ == '__main__':
    asyncio.run(main())
